### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by azeem39** [Eleven-am/frames#3]
Hello, can you please provide a guide on how to set it up on Ubuntu server

**Comment by driftywinds** [comment]
Use docker compose, the setup instructions are in the README

**Comment by C-Fu** [comment]
this kinda works on my machine. need to install docker.

docker-compose.yml:
```
version: '3'

services:
  frames:
    container_name: frames
    image: elevenam/frames:dev
    ports:
      - "3000:3000"
    volumes:
# change /root/media to point to your media folder, with tvshows and movies subfolder in it, and when prompted the movie location in browser type in /media
      - /root/media:/media 
#      - ./app:/usr/src/app
    environment:
      - DATABASE_URL=postgres://frames:password@frame_postgres:5432/frames
      - DIRECT_DATABASE_URL=postgres://frames:password@frame_postgres:5432/frames
      - REDIS_HOST=frame_redis
      - REDIS_PORT=6379
      - REDIS_TTL=86400
      - REDIS_DB=0
      - JWT_SECRET=password
    depends_on:
      - frame_postgres
      - frame_redis

  frame_postgres:
    container_name: frame_postgres
    image: pgvector/pgvector:pg14
    environment:
      - POSTGRES_USER=frames
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=frames
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  frame_redis:
    container_name: frame_redis
    image: redis:alpine
    volumes:
      - ./redis_data:/data
```
